services:
  - type: web
    name: pledge-bloom-app
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run preview -- --host 0.0.0.0
    envVars:
      - key: NODE_ENV
        value: production